# Generated by Django 5.1.4 on 2025-01-27 16:30

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrodesalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'centroDeSalud',
            },
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condicion',
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'patologia',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('calle', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('num_depto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residencia',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('fecha_nac', models.DateTimeField()),
                ('genero', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('terapeuta', 'Terapeuta'), ('paciente', 'Paciente'), ('padre', 'Padre')], default='paciente', max_length=255)),
                ('patologia', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_id_padre', models.ForeignKey(blank=True, db_column='user_id_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
                ('direccion_id_dir', models.ForeignKey(db_column='direccion_id_dir', on_delete=django.db.models.deletion.CASCADE, to='api.residencia')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CentroProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrodesalud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centrodesalud')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'centroProfesional',
            },
        ),
        migrations.CreateModel(
            name='Escena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=40)),
                ('acento', models.CharField(default='neutro', max_length=40)),
                ('complejidad', models.IntegerField()),
                ('link', models.CharField(max_length=2000)),
                ('nombre', models.CharField(default='Sin Nombre', max_length=100)),
                ('condicion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='api.condicion')),
            ],
            options={
                'db_table': 'escena',
            },
        ),
        migrations.AddField(
            model_name='condicion',
            name='escena',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='api.escena'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
                ('visibilidad', models.BooleanField(default=True)),
                ('comentario_contestado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_comentario_contestado', to='api.comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_user', to=settings.AUTH_USER_MODEL)),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_escena', to='api.escena')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='CentroProfesionalEscena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_profesional_id', to='api.centroprofesional')),
                ('escena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escena')),
            ],
            options={
                'db_table': 'centroProfesionalEscena',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_verificacion_automatica', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='FormularioPacienteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_dni', models.CharField(max_length=20)),
                ('revision', models.BooleanField(default=False)),
                ('verificado_automatico', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('volver_a_realizar', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('centrodesalud_id', models.ForeignKey(db_column='centroDeSalud_id', on_delete=django.db.models.deletion.CASCADE, to='api.centrodesalud')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('leida', 'Leída'), ('eliminada', 'Eliminada')], default='pendiente', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
            },
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Sin Nombre', max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('centro_profesional', models.ForeignKey(db_column='centroProfesional_id', on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_centro_salud_id', to='api.centroprofesional')),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivo_explicativo', to='api.escena')),
            ],
            options={
                'db_table': 'objetivo',
            },
        ),
        migrations.CreateModel(
            name='EscenaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escena')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
            ],
            options={
                'db_table': 'escenaObjetivo',
            },
        ),
        migrations.AddField(
            model_name='condicion',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.objetivo'),
        ),
        migrations.CreateModel(
            name='Objetivoscumplir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
                ('objetivo_previo', models.ForeignKey(db_column='objetivo_previo', on_delete=django.db.models.deletion.CASCADE, related_name='objetivoscumplir_objetivo_previo_set', to='api.objetivo')),
            ],
            options={
                'db_table': 'objetivosCumplir',
            },
        ),
        migrations.CreateModel(
            name='Personagrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='api.grupo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagrupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personaGrupo',
            },
        ),
        migrations.CreateModel(
            name='PersonaObjetivoEscena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escena_objetivo', models.ForeignKey(blank=True, db_column='objetivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivo_relations', to='api.escenaobjetivo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personaEscenaObjetivo',
            },
        ),
        migrations.CreateModel(
            name='PersonaObjetivoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('progreso', models.IntegerField()),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formulario')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formulario')),
                ('objetivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personaObjetivoEvaluacion',
            },
        ),
        migrations.CreateModel(
            name='PersonaPatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certeza', models.FloatField(null=True, validators=[api.models.validate_percentage])),
                ('patologia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patologia')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personaPatologia',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('respuesta-corta', 'Respuesta Corta'), ('respuesta-larga', 'Respuesta Larga')], max_length=20)),
                ('correcta', models.CharField(blank=True, max_length=255, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='api.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='centrodesalud',
            name='direccion_id_dir',
            field=models.ForeignKey(db_column='direccion_id_dir', on_delete=django.db.models.deletion.CASCADE, to='api.residencia'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField(null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('intento_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Videosvistos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('escena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videosvistos_escena_id', to='api.escena')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videosvistos_paciente_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videosVistos',
            },
        ),
        migrations.AddConstraint(
            model_name='centroprofesional',
            constraint=models.UniqueConstraint(fields=('centrodesalud', 'profesional'), name='unique_centrodesalud_profesional'),
        ),
        migrations.AddConstraint(
            model_name='comentario',
            constraint=models.UniqueConstraint(fields=('id', 'user', 'escena'), name='unique_escena_user_comentario'),
        ),
        migrations.AddConstraint(
            model_name='centroprofesionalescena',
            constraint=models.UniqueConstraint(fields=('centro_profesional', 'escena_id'), name='unique_centro_salud_profesional_escena'),
        ),
        migrations.AddConstraint(
            model_name='escenaobjetivo',
            constraint=models.UniqueConstraint(fields=('escena', 'objetivo'), name='unique_escena_objetivo'),
        ),
        migrations.AddConstraint(
            model_name='objetivoscumplir',
            constraint=models.UniqueConstraint(fields=('objetivo', 'objetivo_previo'), name='unique_objetivo_objetivo_previo'),
        ),
        migrations.AddConstraint(
            model_name='personagrupo',
            constraint=models.UniqueConstraint(fields=('user_id', 'grupo_id'), name='unique_user_grupo'),
        ),
        migrations.AddConstraint(
            model_name='personaobjetivoescena',
            constraint=models.UniqueConstraint(fields=('user_id', 'escena_objetivo'), name='unique_user_escena_objetivo'),
        ),
        migrations.AddConstraint(
            model_name='personaobjetivoevaluacion',
            constraint=models.UniqueConstraint(fields=('user_id', 'objetivo_id', 'evaluacion'), name='unique_user_objetivo_evaluacion'),
        ),
        migrations.AddConstraint(
            model_name='personapatologia',
            constraint=models.UniqueConstraint(fields=('user_id', 'patologia_id'), name='unique_user_patologia'),
        ),
        migrations.AddConstraint(
            model_name='videosvistos',
            constraint=models.UniqueConstraint(fields=('paciente_id', 'escena_id', 'id'), name='unique_escena_user_videos_vistos'),
        ),
    ]
