# Generated by Django 5.1.4 on 2024-12-27 15:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrodesalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'centroDeSalud',
            },
        ),
        migrations.CreateModel(
            name='Escena',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
                ('complejidad', models.IntegerField()),
                ('link', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'escena',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_dir', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'residencia',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('centrodesalud', models.ForeignKey(db_column='centroDeSalud_id', on_delete=django.db.models.deletion.CASCADE, to='api.centrodesalud')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('resultado_tera', models.TextField(blank=True, null=True)),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.escena')),
            ],
            options={
                'db_table': 'objetivo',
            },
        ),
        migrations.CreateModel(
            name='Personaobjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('progreso', models.IntegerField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
            ],
            options={
                'db_table': 'personaObjetivo',
            },
        ),
        migrations.CreateModel(
            name='Escenavideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('es_alternativo', models.BooleanField()),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escena')),
                ('personaobjetivo_objetivo', models.ForeignKey(blank=True, db_column='personaObjetivo_objetivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenavideo_objetivo', to='api.personaobjetivo')),
                ('personaobjetivo_user', models.ForeignKey(blank=True, db_column='personaObjetivo_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenavideo_user', to='api.personaobjetivo')),
            ],
            options={
                'db_table': 'escenaVideo',
                'unique_together': {('escena', 'personaobjetivo_user', 'personaobjetivo_objetivo')},
            },
        ),
        migrations.AddField(
            model_name='centrodesalud',
            name='direccion_id_dir',
            field=models.ForeignKey(db_column='direccion_id_dir', on_delete=django.db.models.deletion.CASCADE, to='api.residencia'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('fecha_nac', models.DateTimeField()),
                ('genero', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('terapeuta', 'Terapeuta'), ('paciente', 'Paciente'), ('padre', 'Padre')], default='paciente', max_length=255)),
                ('direccion_id_dir', models.ForeignKey(db_column='direccion_id_dir', on_delete=django.db.models.deletion.CASCADE, to='api.residencia')),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_id_padre', models.ForeignKey(blank=True, db_column='user_id_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='personaobjetivo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('escena', models.ForeignKey(db_column='escena_id', on_delete=django.db.models.deletion.CASCADE, to='api.escenavideo')),
                ('personaobjetivo_objetivo', models.ForeignKey(blank=True, db_column='personaObjetivo_objetivo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_como_objetivo', to='api.escenavideo')),
                ('personaobjetivo_user', models.ForeignKey(blank=True, db_column='personaObjetivo_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_como_user', to='api.escenavideo')),
            ],
            options={
                'db_table': 'comentario',
                'unique_together': {('escena', 'personaobjetivo_user', 'personaobjetivo_objetivo')},
            },
        ),
        migrations.CreateModel(
            name='Objetivoscumplir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
                ('objetivo_previo', models.ForeignKey(db_column='objetivo_previo', on_delete=django.db.models.deletion.CASCADE, related_name='objetivoscumplir_objetivo_previo_set', to='api.objetivo')),
            ],
            options={
                'db_table': 'objetivosCumplir',
                'unique_together': {('objetivo', 'objetivo_previo')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('personaobjetivo_objetivo', models.ForeignKey(db_column='personaObjetivo_objetivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_objetivo', to='api.personaobjetivo')),
                ('personaobjetivo_user', models.ForeignKey(db_column='personaObjetivo_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_user', to='api.personaobjetivo')),
            ],
            options={
                'db_table': 'evaluacion',
                'unique_together': {('personaobjetivo_user', 'personaobjetivo_objetivo')},
            },
        ),
        migrations.CreateModel(
            name='Terapeutagrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'terapeutaGrupo',
                'unique_together': {('user', 'grupo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='personaobjetivo',
            unique_together={('user', 'objetivo')},
        ),
        migrations.CreateModel(
            name='Personagrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='api.grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagrupos', to='api.user')),
            ],
            options={
                'db_table': 'personaGrupo',
                'unique_together': {('user', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='Videosvistos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escena', models.ForeignKey(db_column='escena_id', on_delete=django.db.models.deletion.CASCADE, to='api.escenavideo')),
                ('personaobjetivo_objetivo', models.ForeignKey(blank=True, db_column='personaObjetivo_objetivo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_vistos_como_objetivo', to='api.escenavideo')),
                ('personaobjetivo_user', models.ForeignKey(blank=True, db_column='personaObjetivo_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_vistos_como_user', to='api.escenavideo')),
            ],
            options={
                'db_table': 'videosVistos',
                'unique_together': {('escena', 'personaobjetivo_user', 'personaobjetivo_objetivo')},
            },
        ),
    ]
