# Generated by Django 5.1.4 on 2025-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
