# Generated by Django 5.1.4 on 2025-02-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='objetivo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo', to='api.objetivo'),
        ),
        migrations.AlterField(
            model_name='personaobjetivoescena',
            name='escena_objetivo',
            field=models.ForeignKey(blank=True, db_column='EscenaObjetivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivo_relations', to='api.escenaobjetivo'),
        ),
    ]
