# Generated by Django 5.1.4 on 2025-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='resultado_tera',
        ),
        migrations.AddField(
            model_name='escena',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=255),
        ),
    ]
