# Generated by Django 5.1.4 on 2025-02-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='escena',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='nombre_escena', to='api.escena'),
        ),
    ]
