# Generated by Django 5.1.4 on 2025-01-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_objetivo_resultado_tera_escena_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escenavideo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='escena',
            name='acento',
            field=models.CharField(default='neutro', max_length=40),
        ),
        migrations.AddField(
            model_name='escenavideo',
            name='personaobjetivo_evaluacion',
            field=models.ForeignKey(blank=True, db_column='personaObjetivo_evaluacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenavideo_evaluacion', to='api.personaobjetivo'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='escena',
            name='idioma',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='escena',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='escena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivo_explicativo', to='api.escena'),
        ),
        migrations.AlterUniqueTogether(
            name='escenavideo',
            unique_together={('escena', 'personaobjetivo_user', 'personaobjetivo_objetivo', 'personaobjetivo_evaluacion')},
        ),
        migrations.CreateModel(
            name='EscenaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escena')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetivo')),
            ],
            options={
                'db_table': 'EscenaObjetivo',
                'unique_together': {('escena', 'objetivo')},
            },
        ),
    ]
