# Generated by Django 5.1.4 on 2025-01-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formulario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario',
            table='formulario',
        ),
    ]
