# Generated by Django 5.1.4 on 2025-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_escena_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
