# Generated by Django 5.1.4 on 2025-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_objetivo_resultado_tera_escena_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='visibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
