# Generated by Django 5.1.4 on 2025-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_objetivo_resultado_tera_escena_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodesalud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
