# Generated by Django 5.1.4 on 2025-02-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_formulario_escena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='escena',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='escena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nombre_escena', to='api.escena'),
        ),
    ]
