# Generated by Django 5.1.4 on 2025-01-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_formulario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario',
            table=None,
        ),
    ]
