# Generated by Django 5.1.4 on 2025-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_objetivo_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
