# Generated by Django 5.1.4 on 2025-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_centrodesalud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='id_dir',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
