# Generated by Django 5.1.4 on 2025-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formulario_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escena',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100, unique=True),
        ),
    ]
