services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base_datos_tea
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    image: backend
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    user: root # ! borrar
    build:
      context: ./frontend
    container_name: nextjs_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontapp:/app
      - /app/node_modules # Excluye node_modules para que Docker las gestione
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  redis:
    image: redis:6.2
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:    
    image: backend
    container_name: celery
    command: celery -A backendapp worker --loglevel=info
    depends_on:      
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:    
    image: backend
    container_name: celery_beat
    command: celery -A backendapp beat --loglevel=info
    depends_on:      
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  db_data: