version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base_datos_tea
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontapp:/app
      - /app/node_modules # Excluye node_modules para que Docker las gestione
    depends_on:
      - backend

volumes:
  db_data:
