import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";
import { wrapper } from "../../store/store"; // Importa el wrapper

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header />
        </header>
        <main className="mt-14">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}

export default wrapper.withRedux(RootLayout);
