import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";

// Asegúrate de importar ReduxProvider desde la ruta correcta
import ReduxProvider from "../../store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* ReduxProvider debe envolver todos los componentes que usan Redux */}
        <ReduxProvider>
          <Header />
          <main className="mt-14 flex-grow">{children}</main>
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
