import type { Metadata } from "next";

import { Inter } from 'next/font/google';
// import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";
import SideNav from "../components/SideNav";
import MarginWidthWrapper from "../components/MarginWidthWrapper";
import HeaderMobile from "../components/MobileHeader";
import PageWrapper from "../components/PageWrapper";

// Asegúrate de importar ReduxProvider desde la ruta correcta
import ReduxProvider from "../../store/provider";

const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-white ${inter.className}`}>
        {/* ReduxProvider debe envolver todos los componentes que usan Redux */}
        <ReduxProvider>
        <Header /> {/* Asegúrate de que esté fuera del contenedor flex */}
        <div className="flex pt-[47px]">
          <SideNav />
          <main className="flex-1 mt-14">
            <MarginWidthWrapper>
              <HeaderMobile />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
            </ReduxProvider>
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }){
//   return (
//     <html lang="en">
//       <body className={`bg-white ${inter.className}`}>
//         <div className="flex">
//           <SideNav />
//           <main className="flex-1">
//             <MarginWidthWrapper>
//               <MenuHeader /> {/*aca va el header real*/}
//               <HeaderMobile />
//               <PageWrapper>{children}</PageWrapper>
//             </MarginWidthWrapper>
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }
